version: '3'
services:
  server:
    build: 
      context: ./Backend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - "database"
      # <host machine port> : <container port>
      # you can use the same container port but different host ports.
  client:
    build: 
      context: ./complete
      dockerfile: dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - "server"

  database:
    build: 
      context: ./database
      dockerfile: dockerfile
    ports:
      - "3307:3306"