import LeftNavbar from "@/app/dashboard/LeftNavbar"
import "@/styles/index.css"

export const metadata = {
  title: 'dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='relative flex h-screen w-screen'>
        <LeftNavbar />
        <div className="w-full relative h-screen overflow-hidden">
          {children}
        </div>
      </body>
    </html>
  )
}